[package]
name = "ipc-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
# Import the Cap'N Proto schemas for Bitcoin Core v31.0.
bitcoin-capnp-types = { git = "https://github.com/xyzconstant/bitcoin-capnp-types", rev = "243378ad93efb7d73d7d47fe82703e900a1ee457" }
shared = { path = "../../shared" }

[features]
# Treat warnings as a build error.
strict = []

# Run integration tests needing a NATS server.
nats_integration_tests = []

# Run integration tests needing a Bitcoin Core node.
node_integration_tests = []
